name: 'mujahid_dv_databricks'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks_dv'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  mujahid_dv_databricks:
    +materialized: table
    +file_format: delta
    
    staging:
      +schema: staging
      +materialized: incremental
      +on_schema_change: 'append_new_columns'
      +tags: ['staging', 'psa']
      
    raw_vault:
      +schema: raw_vault
      +materialized: incremental
      +tags: ['raw_vault']
      
      hubs:
        +tags: ['hub']
        
      links:
        +tags: ['link']
        
      satellites:
        +tags: ['satellite']
        
    business_vault:
      +schema: business_vault
      +materialized: table
      +tags: ['business_vault']
      
    information_marts:
      +schema: information_marts
      +materialized: table
      +tags: ['mart']

# Variable configurations
vars:
  load_date: '1992-01-08'
  beginning_of_all_times: '1970-01-01'
  # Hash algorithm for Data Vault
  hash: 'MD5'
  
# Seeds configuration
seeds:
  mujahid_dv_databricks:
    +schema: staging

