name: 'mujahid_dv_databricks'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks_dv'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  mujahid_dv_databricks:
    +materialized: table
    +file_format: delta
    
    # 🥉 BRONZE LAYER - PSA (Persistent Staging Area)
    staging:
      +schema: bronze_psa
      +materialized: incremental
      +on_schema_change: 'append_new_columns'
      +tags: ['bronze', 'psa']
      
    # 🥈 SILVER LAYER - Raw Vault (Curated Data Vault)
    raw_vault:
      +schema: silver_raw_vault
      +materialized: incremental
      +tags: ['silver', 'raw_vault']
      
      hubs:
        +tags: ['hub']
        
      links:
        +tags: ['link']
        
      satellites:
        +tags: ['satellite']
    
    # 🥈 SILVER LAYER - Business Vault (Business Logic)
    business_vault:
      +schema: silver_business_vault
      +materialized: table
      +tags: ['silver', 'business_vault']
      
    # 🥇 GOLD LAYER - Information Marts (Analytics)
    information_marts:
      +schema: gold_information_marts
      +materialized: table
      +tags: ['gold', 'marts']

# Variable configurations
vars:
  load_date: '1992-01-08'
  beginning_of_all_times: '1970-01-01'
  # Hash algorithm for Data Vault
  hash: 'MD5'
  
# Seeds configuration
seeds:
  mujahid_dv_databricks:
    +schema: staging

