databricks_dv:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: mujahid_data_vault_demo
      schema: staging  # default schema
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 4
      
    prod:
      type: databricks
      catalog: mujahid_data_vault_demo
      schema: staging
      host: "{{ env_var('DBT_DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DBT_DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DBT_DATABRICKS_TOKEN') }}"
      threads: 8

