version: 2

sources:
  - name: tpch
    description: TPC-H benchmark dataset from Databricks samples catalog
    database: samples
    schema: tpch
    tables:
      - name: customer
        description: Customer dimension from TPC-H
        columns:
          - name: c_custkey
            description: Customer key (primary key)
          - name: c_name
            description: Customer name
          - name: c_address
            description: Customer address
          - name: c_nationkey
            description: Nation key (foreign key)
          - name: c_phone
            description: Customer phone
          - name: c_acctbal
            description: Account balance
          - name: c_mktsegment
            description: Market segment
          - name: c_comment
            description: Customer comment
            
      - name: orders
        description: Orders fact table from TPC-H
        columns:
          - name: o_orderkey
            description: Order key (primary key)
          - name: o_custkey
            description: Customer key (foreign key)
          - name: o_orderstatus
            description: Order status
          - name: o_totalprice
            description: Total price
          - name: o_orderdate
            description: Order date
          - name: o_orderpriority
            description: Order priority
          - name: o_clerk
            description: Clerk
          - name: o_shippriority
            description: Ship priority
          - name: o_comment
            description: Order comment
            
      - name: lineitem
        description: Line item fact table from TPC-H
        columns:
          - name: l_orderkey
            description: Order key (foreign key)
          - name: l_partkey
            description: Part key (foreign key)
          - name: l_suppkey
            description: Supplier key (foreign key)
          - name: l_linenumber
            description: Line number
          - name: l_quantity
            description: Quantity
          - name: l_extendedprice
            description: Extended price
          - name: l_discount
            description: Discount
          - name: l_tax
            description: Tax
          - name: l_returnflag
            description: Return flag
          - name: l_linestatus
            description: Line status
          - name: l_shipdate
            description: Ship date
          - name: l_commitdate
            description: Commit date
          - name: l_receiptdate
            description: Receipt date
          - name: l_shipinstruct
            description: Ship instructions
          - name: l_shipmode
            description: Ship mode
          - name: l_comment
            description: Line item comment
            
      - name: part
        description: Part dimension from TPC-H
        columns:
          - name: p_partkey
            description: Part key (primary key)
          - name: p_name
            description: Part name
          - name: p_mfgr
            description: Manufacturer
          - name: p_brand
            description: Brand
          - name: p_type
            description: Type
          - name: p_size
            description: Size
          - name: p_container
            description: Container
          - name: p_retailprice
            description: Retail price
          - name: p_comment
            description: Part comment
            
      - name: supplier
        description: Supplier dimension from TPC-H
        columns:
          - name: s_suppkey
            description: Supplier key (primary key)
          - name: s_name
            description: Supplier name
          - name: s_address
            description: Supplier address
          - name: s_nationkey
            description: Nation key (foreign key)
          - name: s_phone
            description: Supplier phone
          - name: s_acctbal
            description: Account balance
          - name: s_comment
            description: Supplier comment
            
      - name: partsupp
        description: Part supplier relationship from TPC-H
        columns:
          - name: ps_partkey
            description: Part key (foreign key)
          - name: ps_suppkey
            description: Supplier key (foreign key)
          - name: ps_availqty
            description: Available quantity
          - name: ps_supplycost
            description: Supply cost
          - name: ps_comment
            description: Part supplier comment
            
      - name: nation
        description: Nation dimension from TPC-H
        columns:
          - name: n_nationkey
            description: Nation key (primary key)
          - name: n_name
            description: Nation name
          - name: n_regionkey
            description: Region key (foreign key)
          - name: n_comment
            description: Nation comment
            
      - name: region
        description: Region dimension from TPC-H
        columns:
          - name: r_regionkey
            description: Region key (primary key)
          - name: r_name
            description: Region name
          - name: r_comment
            description: Region comment

