version: 2

models:
  - name: stg_customer
    description: Staged customer data with hash keys
    columns:
      - name: CUSTOMER_PK
        description: Customer primary key hash
        tests:
          - not_null
          - unique
      - name: C_CUSTKEY
        description: Customer business key
        tests:
          - not_null
      - name: CUSTOMER_HASHDIFF
        description: Hash diff for change detection
        tests:
          - not_null
          
  - name: stg_orders
    description: Staged orders data with hash keys
    columns:
      - name: ORDER_PK
        description: Order primary key hash
        tests:
          - not_null
          - unique
      - name: O_ORDERKEY
        description: Order business key
        tests:
          - not_null
      - name: CUSTOMER_ORDER_FK
        description: Customer-Order foreign key hash
        tests:
          - not_null
          
  - name: stg_lineitem
    description: Staged line item data with hash keys
    columns:
      - name: LINEITEM_PK
        description: Line item primary key hash
        tests:
          - not_null
          - unique
      - name: ORDER_LINEITEM_FK
        description: Order-LineItem foreign key hash
        tests:
          - not_null
          
  - name: stg_part
    description: Staged part data with hash keys
    columns:
      - name: PART_PK
        description: Part primary key hash
        tests:
          - not_null
          - unique
      - name: P_PARTKEY
        description: Part business key
        tests:
          - not_null
          
  - name: stg_supplier
    description: Staged supplier data with hash keys
    columns:
      - name: SUPPLIER_PK
        description: Supplier primary key hash
        tests:
          - not_null
          - unique
      - name: S_SUPPKEY
        description: Supplier business key
        tests:
          - not_null
          
  - name: stg_nation
    description: Staged nation data with hash keys
    columns:
      - name: NATION_PK
        description: Nation primary key hash
        tests:
          - not_null
          - unique
      - name: N_NATIONKEY
        description: Nation business key
        tests:
          - not_null
          
  - name: stg_region
    description: Staged region data with hash keys
    columns:
      - name: REGION_PK
        description: Region primary key hash
        tests:
          - not_null
          - unique
      - name: R_REGIONKEY
        description: Region business key
        tests:
          - not_null
          
  - name: stg_partsupp
    description: Staged part-supplier data with hash keys
    columns:
      - name: PARTSUPP_PK
        description: Part-Supplier primary key hash
        tests:
          - not_null
          - unique
      - name: PART_SUPPLIER_FK
        description: Part-Supplier foreign key hash
        tests:
          - not_null

